### ISSUE TITLE
UnexpectedValueException: callback 'SimpleBatchUpload\SimpleBatchUpload::initCallback' is not callable

### ISSUE THREAD

**Issue by s7eph4n** [ProfessionalWiki/SimpleBatchUpload#22]
breaks on Mediawiki 1.31.0

`PHP Fatal error:  Uncaught UnexpectedValueException: callback 'SimpleBatchUpload\SimpleBatchUpload::initCallback' is not callable in /home/riotawfb/nosubject.com/includes/registration/ExtensionRegistry.php:360`

**Comment by thijskh** [comment]
This has been fixed in the meantime.
