### ISSUE TITLE
Repo moved

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/SimpleBatchUpload#26]
@translatewiki please beware that this repo moved. This should not break anything due to a redirect. You also should have the same access as before. Still, you might want to update the relevant config. Let me know if something broke.

**Comment by Nikerabbit** [comment]
From where? I don't find this in our list. Is https://github.com/cmln/mw-scss.git also moved?

**Comment by kghbln** [comment]
> From where? I don't find this in our list.

This extension was not supported by twn, so nothing to move here. 

> Is https://github.com/cmln/mw-scss.git also moved?

"mw-scss" however has indeed moved. I will create a respective issue over there.

**Comment by kghbln** [comment]
Done with https://github.com/ProfessionalWiki/mw-scss/issues/1

**Comment by JeroenDeDauw** [comment]
Oops my bad. I thought this extension was already non TWN.

**Comment by s7eph4n** [comment]
Never got around to that, sorry.

**Comment by kghbln** [comment]
No worries. This is on my list: https://github.com/ProfessionalWiki/SimpleBatchUpload/issues/27
