### ISSUE TITLE
Explanation needed what's going on here

### ISSUE THREAD

**Issue by jkpubsrc** [ProfessionalWiki/SimpleBatchUpload#47]
The upload is performed as soon as you drop a file. This is quite irritating and breaks with common behavior people expect.

There are two options:

a) Describe this in the special page, or better
b) implement this as a two step process: First drop all files, then click a button, then the upload is performed the way it is performed now.

Additionally I noticed that some uploads failed though I have seen no error message in response to an upload.

**Comment by s7eph4n** [comment]
This is the first time this comes up, so I think users' expectations regarding the behavior vary. But it is a fair point.
I would not like to see the two step process, though. The incentive to develop this extension was to allow for the upload of a batch of files every few days in as few mouse clicks as possible. So a two step process would be a step in the wrong direction.

**Comment by jkpubsrc** [comment]
> I would not like to see the two step process, though.

Well, any kind of upload typically is a two-step process: You perform the selections you intend to, provide the data you intend to, then click some kind of "submit" button. This conforms to regular dialog behavior in applications: You are presented with options, then select either "cancel" or "okay" to either drop your changes or make them persistent. The regular MediaWiki upload is no different.

> The incentive to develop this extension was to allow for the upload of a batch of files every few days in as few mouse clicks as possible.

Yes, I considered that. That's why I'd expect to read some kind of text that describes the process in a few words. Users using this extensions will have no mind reading abilities: They like to learn about what's going on *before* some action is taken. This is even more important as all changes made are immediate: A file dropped is uploaded immediately. As this behavior does not meet the standard behavior one would expect, reading some kind of description on the upload page would be a very good thing.

However please note that some uploads failed without notice. I learned it the hard way: The images uploaded did not show on the page. After investigation I understood that some images have not been uploaded though indicated otherwise.

And additionally - not mentioned above - to accept drag and drop did take a very long time for a larger amount of files.

However, thank you very much for this extension. Don't get me wrong: I like it ;-)

**Comment by s7eph4n** [comment]
As a wiki owner, why would you use this extension if what it produces does not match your expectation? If you need images classified individually, then surly you would not make this extension available to your users.
In any case, changing the documentation should be easy enough. Go right ahead.

**Comment by s7eph4n** [comment]
Ok, I understand your use case. But that's not the use case this extension addresses.
