### ISSUE TITLE
Question: The 2.0 Release?

### ISSUE THREAD

**Issue by MPThLee** [ProfessionalWiki/SimpleBatchUpload#55]
### Setup

- MW version: 1.39
- PHP version: PHP 8.1
- DB (MySQL etc.): MariaDB
- SBL version: 1.9

### Issue

Since I'm planning to upgrade php 8.1 on wiki, SimpleBatchUpload need to update 2.0 (which is under development stage, according to release notes). Is there any release date of 2.0?

**Comment by malberts** [comment]
Thanks for the reminder! Version 2.0.0 is out now.
